name: CI/CD for project_UFS

on:
  push:
    paths:
      - 'project_UFS/**'
  pull_request:
    paths:
      - 'project_UFS/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest project_UFS/tests/
