name: CI/CD for Chat Service

on:
  push:
    paths:
      - 'chat/**'
  pull_request:
    paths:
      - 'chat/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --max-line-length=88 --ignore=W391 chat/

      - name: Run security tests with bandit
        run: |
          pip install bandit
          bandit -r chat/

      - name: Install pytest-cov
        run: |
          pip install pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=chat --cov-fail-under=80 chat/tests/

      - name: Generate HTML coverage report
        run: |
          pytest --cov=chat --cov-report=html chat/tests/

      - name: Store coverage report
        uses: actions/upload-artifact@v4  # Version mise à jour
        with:
          name: coverage-report
          path: htmlcov/
          
  docker:
    runs-on: ubuntu-latest
    needs: build  # Ce job dépend du job de build précédent

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # Utilise le nom d'utilisateur GitHub
          password: ${{ secrets.MON_GITHUB_TOKEN }}  # Votre secret ici

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest -f Dockerfile .
          
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
